### ISSUE TITLE
Running inference on RGB-D image

### ISSUE THREAD

**Issue by deepak-asink** [GouMinghao/rgb_matters#1]
Great work..
I want to run inference on a RGBD image taken from Intel realsense D435 camera, Can you help me understand the requirements for the same.
I was able to run demo using instructions with the test data provided by GraspNet.

**Comment by GouMinghao** [comment]
Thanks for your question.
You need to convert your result into `rgb` with the same format in [demo.py](https://github.com/GouMinghao/rgb_matters/blob/main/demo.py#L85) .
 If you want to the normal modality, you should also generate `normal` follow the way in [gen_normal.py](https://github.com/GouMinghao/rgb_matters/blob/main/gen_normals.py)
